### ISSUE TITLE
extending docu with possibe variables for templates

### ISSUE THREAD

**Issue by Shaoranlaos** [scm-manager/scm-repository-template-plugin#3]
#### Problem to be solved

There seems to be no description about the possible variables you can use in the templates.
Or am I missunderstanding the plugin?

#### Proposed solution

Add a page in the documentation which describes the usable variables in the mustache templates.

**Comment by pfeuffer** [comment]
For documentation we have this page: https://www.scm-manager.org/plugins/scm-repository-template-plugin/docs/1.0.x/en/usage/

You are right, the concrete variables are not listed here.

For now you can use attributes of the repository object. Right now this is
- `namespace`
- `name`
- `type`
- `contact`
- `description`
- `id`
